name: reachbot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py38h06a4308_0
  - python=3.8.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - appdirs==1.4.4
      - boto3==1.28.42
      - botocore==1.31.42
      - cachetools==5.3.1
      - certifi==2023.7.22
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - click==8.1.7
      - configparser==6.0.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - dowel==0.0.4
      - fonttools==4.42.1
      - gitdb==4.0.10
      - gitpython==3.1.34
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.57.0
      - idna==3.4
      - imageio==2.31.3
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - jmespath==1.0.1
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - mmcv==2.0.1
      - mmdet==3.1.0
      - mmengine==0.8.4
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - opencv-python==4.8.0.76
      - packaging==23.1
      - pathtools==0.1.2
      - pillow==10.0.0
      - platformdirs==3.10.0
      - prettytable==3.8.0
      - protobuf==4.24.2
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rsa==4.9
      - s3transfer==0.6.2
      - scikit-image==0.21.0
      - scipy==1.10.1
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - shapely==2.0.1
      - six==1.16.0
      - smmap==5.0.0
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.2.2
      - termcolor==2.3.0
      - terminaltables==3.1.10
      - tifffile==2023.7.10
      - tomli==2.0.1
      - toolbox==0.4.3
      - torch==1.7.1+cu110
      - torchaudio==0.7.2
      - torchvision==0.8.2+cu110
      - typing-extensions==4.7.1
      - urllib3==1.26.16
      - wandb==0.15.10
      - wcwidth==0.2.6
      - werkzeug==2.3.7
      - yapf==0.40.1
      - zipp==3.16.2